// Roadmap 1.1 — Argon2id master_key derivation.
import { test } from 'node:test';
import assert from 'node:assert/strict';

import { deriveMasterKey, ARGON2_PARAMS } from '../lib/crypto/argon2.js';
import { generateSalt } from '../lib/crypto/random.js';
import { bytesEqual, fromBase64Url, toBase64Url } from '../lib/crypto/encoding.js';

const SALT_A = fromBase64Url('AAECAwQFBgcICQoLDA0ODw');
const SALT_B = fromBase64Url('8PDw8PDw8PDw8PDw8PDw8A');

test('parameters match design Section 2.1 exactly', () => {
  assert.deepEqual({ ...ARGON2_PARAMS }, {
    memorySizeKiB: 65536,
    iterations: 3,
    parallelism: 1,
    hashLengthBytes: 32,
  });
});

test('known vector — pinned so a parameter change cannot pass silently', async () => {
  // Not an upstream test vector; generated by this implementation and frozen.
  // Its job is to fail loudly if the params, the library, or the salt encoding
  // ever drift, because any of those locks every existing user out of their vault.
  const key = await deriveMasterKey('correct horse battery staple', SALT_A);
  assert.equal(toBase64Url(key), 'DRo8ZSPI8G5OCvnFFapbVEjP69aDjy1Sw9i2743cPC4');
});

test('deterministic: same password and salt produce the same key', async () => {
  const first = await deriveMasterKey('hunter2 hunter2 hunter2', SALT_A);
  const second = await deriveMasterKey('hunter2 hunter2 hunter2', SALT_A);

  assert.equal(first.length, 32);
  assert.ok(bytesEqual(first, second));
});

test('different salt produces a different key for the same password', async () => {
  const withA = await deriveMasterKey('hunter2 hunter2 hunter2', SALT_A);
  const withB = await deriveMasterKey('hunter2 hunter2 hunter2', SALT_B);

  assert.ok(!bytesEqual(withA, withB));
});

test('different password produces a different key for the same salt', async () => {
  const first = await deriveMasterKey('hunter2 hunter2 hunter2', SALT_A);
  const second = await deriveMasterKey('hunter2 hunter2 hunter3', SALT_A);

  assert.ok(!bytesEqual(first, second));
});

test('rejects a salt that is not 16 bytes', async () => {
  await assert.rejects(() => deriveMasterKey('password', new Uint8Array(8)), TypeError);
  await assert.rejects(() => deriveMasterKey('password', generateSalt().subarray(0, 15)), TypeError);
});

test('rejects an empty password', async () => {
  await assert.rejects(() => deriveMasterKey('', SALT_A), TypeError);
});
