/**
 * Produces `docs/vectors/records-v1.json`, the known-answer vectors published
 * with `docs/protocol.md` (roadmap 4.7).
 *
 *   node scripts/generate-vectors.js        writes the file
 *   node scripts/generate-vectors.js --check  prints it, writes nothing
 *
 * **The vectors are generated by the shipped modules, not by a copy of them.**
 * A vector file written alongside the implementation would agree with the
 * implementation's bugs, and a port that reproduced it would inherit them; this
 * imports `lib/crypto/` through the same path the browser does, and
 * `test/protocol-vectors.test.js` then re-derives every value in the file from
 * scratch on every `npm test`. So the file cannot drift from the code, and the
 * document quoting it cannot drift from either.
 *
 * Every input here is fixed and public. `DEVICE_SECRET` below is a published
 * test value and must never be used by a real device: everything derived from
 * it, including the signing key, is in this repository.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import {
  deriveDeviceDataKey,
  deriveDeviceSignSeed,
  ed25519PublicKeyFromSeed,
  ed25519Sign,
  encodeCbor,
  encryptRecord,
  composeSeq,
  recordSigningInput,
  toBase64Url,
  PROTOCOL_VERSION,
  RECORD_TYPE_V1,
} from '../lib/crypto/index.js';

/** All-public test inputs. `DEVICE_SECRET` is 0x00..0x1f, `DEVICE_ID` is 0xa0.. */
const DEVICE_SECRET = Uint8Array.from({ length: 32 }, (_, i) => i);
const DEVICE_ID = Uint8Array.from({ length: 16 }, (_, i) => 0xa0 + i);

/**
 * Two records from the same device, chosen to exercise the two things a port
 * gets wrong: the first is boot 1 message 0, the smallest legal `seq` a device
 * can produce; the second crosses into a `boot_epoch` high enough that the
 * composed `seq` leaves the JS safe-integer range, which is where a port that
 * used a double instead of a uint64 stops matching.
 */
const RECORDS = [
  {
    label: 'first record of the first boot',
    bootEpoch: 1,
    msgCounter: 0,
    payload: { t: 1786000000, r: { temp_c: 21.5, humidity: 48, heater: false } },
  },
  {
    label: 'a boot_epoch past 2^21, where seq stops fitting in a double',
    bootEpoch: 4000000,
    msgCounter: 7,
    payload: { t: 1786003600, r: { temp_c: -3.25, humidity: 91, heater: true } },
  },
];

const hex = (bytes) => Buffer.from(bytes).toString('hex');

async function build() {
  const dataKey = await deriveDeviceDataKey(DEVICE_SECRET);
  const signSeed = await deriveDeviceSignSeed(DEVICE_SECRET);
  const signPub = await ed25519PublicKeyFromSeed(signSeed);

  const records = [];
  for (const record of RECORDS) {
    const seq = composeSeq(record.bootEpoch, record.msgCounter);
    const payloadCbor = encodeCbor(record.payload);
    const { nonce, ciphertext, aad } = await encryptRecord({
      dataKey,
      deviceId: DEVICE_ID,
      seq,
      payload: record.payload,
    });
    const signature = await ed25519Sign(signSeed, recordSigningInput(aad, nonce, ciphertext));

    records.push({
      label: record.label,
      boot_epoch: record.bootEpoch,
      msg_counter: record.msgCounter,
      seq: seq.toString(),
      payload: record.payload,
      payload_cbor_hex: hex(payloadCbor),
      aad_hex: hex(aad),
      nonce_hex: hex(nonce),
      ciphertext_hex: hex(ciphertext),
      sig_hex: hex(signature),
      // What a conforming client actually posts, so a port can diff its own
      // request body against a known-good one rather than against a description.
      post_records_body: {
        device_id: toBase64Url(DEVICE_ID),
        seq: seq.toString(),
        nonce: toBase64Url(nonce),
        ciphertext: toBase64Url(ciphertext),
        sig: toBase64Url(signature),
      },
    });
  }

  return {
    $comment:
      'Known-answer vectors for the SIoT device wire protocol v1. Generated by ' +
      'frontend/scripts/generate-vectors.js from frontend/lib/crypto and verified on every ' +
      'npm test by frontend/test/protocol-vectors.test.js. The DEVICE_SECRET here is public: ' +
      'never provision a real device with it.',
    protocol_version: PROTOCOL_VERSION,
    record_type: RECORD_TYPE_V1,
    device: {
      device_secret_hex: hex(DEVICE_SECRET),
      device_id_hex: hex(DEVICE_ID),
      device_id_b64url: toBase64Url(DEVICE_ID),
      hkdf: {
        algorithm: 'HKDF-SHA256, empty salt, 32-byte output',
        data_key_info: 'siot/device/data/v1',
        sign_seed_info: 'siot/device/sign/v1',
      },
      device_data_key_hex: hex(dataKey),
      ed25519_seed_hex: hex(signSeed),
      sign_pub_hex: hex(signPub),
      sign_pub_b64url: toBase64Url(signPub),
    },
    records,
  };
}

const vectors = await build();
const json = `${JSON.stringify(vectors, null, 2)}\n`;

if (process.argv.includes('--check')) {
  process.stdout.write(json);
} else {
  const out = fileURLToPath(new URL('../../docs/vectors/records-v1.json', import.meta.url));
  writeFileSync(out, json);
  process.stdout.write(`wrote ${out}\n`);
}
